// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg5sROb29JYA5htKfcfcVU3-qe_JtStJY',
    appId: '1:567567072435:web:628f8848e7ec6aa72c84c6',
    messagingSenderId: '567567072435',
    projectId: 'notes-app-c165a',
    authDomain: 'notes-app-c165a.firebaseapp.com',
    storageBucket: 'notes-app-c165a.appspot.com',
    measurementId: 'G-JFY4CV15V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-46z4iUMawQ6e5c0dwzGp1GjSRJ0OdME',
    appId: '1:567567072435:android:ed6d643d6487cb612c84c6',
    messagingSenderId: '567567072435',
    projectId: 'notes-app-c165a',
    storageBucket: 'notes-app-c165a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAScV6lNzheLujV_pnzXtOsA9w9e-NLs_g',
    appId: '1:567567072435:ios:41cc1a398f484f432c84c6',
    messagingSenderId: '567567072435',
    projectId: 'notes-app-c165a',
    storageBucket: 'notes-app-c165a.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );
}
